### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by willshowell** [angular/material-prefix-updater#1]
First, @DevVersion & @jelbourn, this is awesome. I _really_ appreciate how easy it was to upgrade. The only two things it missed were a `ViewChild` reference and some wildcard imports, both of which are pretty edge cases. 

I assume this tool will be used a lot for the presubmit process, so maybe this feedback will help!

1. A template ref was updated but the `ViewChild` selector was not

```diff
- <md-sidenav #mdMenuSidenav>...</md-sidenav>
+ <mat-sidenav #matMenuSidenav>...</mat-sidenav>

...

-  @ViewChild('mdMenuSidenav') menuSidenav: MdSidenav;
+  @ViewChild('mdMenuSidenav') menuSidenav: MatSidenav;
```

2. The way I'm importing Material modules is kinda lazy. I can understand why this was not caught, but maybe it could be?

```ts
import * as md from '@angular/material';

const MATERIAL_MODULES = [
  md.MdAutocompleteModule,
  md.MdButtonModule,
  md.MdButtonToggleModule,
  md.MdCardModule,
  md.MdChipsModule,
  md.MdCheckboxModule,
  md.MdDatepickerModule,
  md.MdDialogModule,
  md.MdExpansionModule,
  md.MdGridListModule,
  md.MdIconModule,
  md.MdInputModule,
  md.MdListModule,
  md.MdMenuModule,
  md.MdNativeDateModule,
  md.MdPaginatorModule,
  md.MdProgressBarModule,
  md.MdProgressSpinnerModule,
  md.MdRadioModule,
  md.MdRippleModule,
  md.MdSelectModule,
  md.MdSidenavModule,
  md.MdSliderModule,
  md.MdSlideToggleModule,
  md.MdSnackBarModule,
  md.MdSortModule,
  md.MdTableModule,
  md.MdTabsModule,
  md.MdToolbarModule,
  md.MdTooltipModule,
];
```

Finally, some initial output/feedback when running the CLI would be nice 😄 I wasn't immediately sure if it was working or hanging. Alternatively, instead of `spawnSync`, it would be cool if the changed files were output in realtime, so you can tell it's still working smoothly.

**Comment by jelbourn** [comment]
We actually just finished migrating Google apps today (we've been using a slightly modified version internally so we could start the migration sooner). 

The template variable thing we should fix. 

I'm not sure how hard the `import *` thing would be to fix- @DevVersion thoughts? If it would be time consuming we can probably tolerate that case.

**Comment by matheo** [comment]
After I used the updater I'm getting this error: `Error: The "mat-" prefix cannot be used in ng-material v1 compatibility mode. It was used on an "mat-sidenav-container" element.` I don't know why `mat-` is being banned instead `md-` here:
https://github.com/angular/material2/blob/3571f68a2de0833ee4741af8a0eb24d1da174f38/src/lib/core/compatibility/compatibility.ts#L197

I have to import `NoConflictStyleCompatibilityMode` in my root module to be able to run.
 
In the other hand, there is a rename from MatSort that is not being performed on `.ts`:
```
mdSortChange => sortChange
```

Styles are not converted? or were `scss` forgotten?
IMHO it's kinda safe to rename `md-` on styles too.

**Comment by DevVersion** [comment]
@willshowell Thanks for the issue. Not sure if it's something that the tool can/should fix.

```diff
- <md-sidenav #mdMenuSidenav>...</md-sidenav>
+ <mat-sidenav #matMenuSidenav>...</mat-sidenav>

...

-  @ViewChild('mdMenuSidenav') menuSidenav: MdSidenav;
+  @ViewChild('mdMenuSidenav') menuSidenav: MatSidenav;
```

The `#mdMenuSidenav` seems to be a template variable, which is defined with whatever name the developers specifies. This means that this is not something that is from Material. 

For example, the template variable could be also named `#my-sidenav`.

The tool only changes the prefixes for "tokens" that are really part of Angular Material. But `mdMenuSidenav` is not part of Angular Material and therefore won't be updated because it's something that has been just named like that by the developer.

In general the use of the `md`/`mat` prefix for something that isn't part of Angular Material should be avoided.

For the namespace imports, I've filed a PR that addressed that issue #2

**Comment by willshowell** [comment]
@DevVersion yeah tbh I don't know why I named it that (and I've renamed it since 😄 ). My concern was more about how the tool *did* update the name of the template variable but *did not* update the ViewChild selector. 

The expected behavior would be that it did neither.

**Comment by willshowell** [comment]
But I also understand how much of an edge case both of these are. Those problems took 45 seconds total to fix in my project.

**Comment by DevVersion** [comment]
@willshowell Yeah totally agree with that. The problem is that we are doing a very lazy search & replace for most of the things in the HTML files. 

This means that "**mdMenu**Sidenav" is replaced accidentally because of the `mdMenu`  exportAs literal. 

Not sure if it would be worth making changes to the replacement system to address such an edge case.

**Comment by willshowell** [comment]
Agreed. With #2 and #3, I'm more than content. If, by any chance, other folks come across this in their upgrade, this discussion should encourage them to change their template variable name.
