### ISSUE TITLE
After running mat-switcher, VS Code does not recognize modules as imported

### ISSUE THREAD

**Issue by Soulzityr** [angular/material-prefix-updater#20]
I have an app-material.module.ts that imports several modules for use. However, only one of them is recognized as imported by VS Code.

![image](https://user-images.githubusercontent.com/13813287/33190022-7e5f45b6-d076-11e7-8d15-56854c6c7c1e.png)

The error code for all the red squigglies is "Module ...path... has no exported member 'ModuleName'.

However, I can still run ng serve with @angular/cli and it will successfully compile and build the website.

However, all of my html renderings are broken. I just get a white screen with a grey bar on top, possibly from my header toolbar. By checking all of the changes made by mat-switcher, I see that indeed the only thing that has changed are all my md prefixes to mat prefixes (I only have 9 affected files).

**Comment by DevVersion** [comment]
Hey, I'm not really sure if this is something that is being caused by the tool. The tool just changes the prefixes and updates the corresponding source files.

Be sure to update to the latest version after running the tool. This updates the typings as well, and should therefore make your IDE green again.

If you say that compilation in general works, then I'm pretty sure the tool didn't do anything wrong.
